#include<iostream>
#include<chrono>
using namespace std; 

// recursive function 
int recursive_fib(int n){
        
    if(n <=1 ){
         return n;
    }
    return recursive_fib(n-1) + recursive_fib(n-2);

}

//non-recursive function 
void nonrecursive_fib(int n){
    int n1=0, n2=1, n3;
    if( n < 0 ){
        cout<<"Please enter a valid positive number!!";
        return;
        
    }
     if(n == 0){
        cout<<"No terms to display.\n";
        return;
     }
    if(n == 1){
        cout<<n1<<" ";
        return;
    }
    cout<<n1<<" "<<n2<<" ";
    for(int i=2 ; i<n ;i++){
        n3 = n1 + n2;
        cout<< n3 << " ";
        n1 = n2;
        n2 = n3;
        
    }
    cout<<endl;

}

int main(){
    int n;
    cout<<"Enter the number of terms : ";
    cin>>n;

    cout<<"-----------Fibonacci Series Generated By Recursive Function -------------\n";
    for(int i = 0; i < n; i++){
        cout<<recursive_fib(i)<<" ";
        
    }
    cout<<endl;

    cout<<"-----------Fibonacci Series Generated By Non-Recursive Function -------------\n";
    nonrecursive_fib(n);


}